spring:
  jpa:
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8


excel:
  dept: ;部门
  name: 姓名
  phoneNumber: 分机号;固话;内线
  tellphoneNumber: 手机
  email: E-mail;邮箱
  fex: 传真
  ext: 生日;职务
banner:
  charset: utf-8
server:
  tomcat:
    uri-encoding: UTF-8
logging:
  level:
    org.springframework: off
    org.hibernate: off

#    常量记录
constant:
  mainDept: 叙简科技

